//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOGRENCİ.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class kulupler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kulupler()
        {
            this.ogrenciler = new HashSet<ogrenciler>();
        }
    
        public byte kulup_id { get; set; }
        public string kulup_adi { get; set; }
        public Nullable<short> kulup_kontenjan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogrenciler> ogrenciler { get; set; }
    }
}
